# String, your sendgrid API key
sendGridAPI: ""

# Email to send from
OpenSump_email: ""

# Email(s) to send to
alertRecipients:
  - "example@example.com"

# Email subject line
emailSubject: "OpenSumpAlarm - Liquid Detected!"

# Email contents
emailContent: "A significant rise in water levels was detected! Investigation is encouraged."

# Distance (centimeters) water should be from sensor before triggering a warning
# Integer, most sensors have too much signal noise for accuracy to matter
warnDistance: 20

# Amount of time to read data from the sensor. You probably don't need to change this.
# This is done to prevent false alarms as a result of sensor inaccuracies and temporary rises above safe limits.
readTime: 16.0

# DO NOT CHANGE, automatically managed.
configVersion: 1.0
botName: "OpenSumpAlarm"